### ISSUE TITLE
m1 的版本能压一下么 .我这边老提示报错.

### ISSUE THREAD

**Issue by canddyBrea** [buddy-red/bks-Chinese#1]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/36022865/192713285-3a047032-84fb-4b5d-aed7-26345007f6db.png">

**Comment by buddy-red** [comment]
抱歉！本Repo不对新issue作修复，如果遇到问题请到[原仓库提出>>>](https://github.com/beekeeper-studio/beekeeper-studio/issues)
