### ISSUE TITLE
你好，请问如何安装

### ISSUE THREAD

**Issue by anicetrip** [buddy-red/bks-Chinese#2]

**Comment by buddy-red** [comment]
本Repo不提供技术支持，请到[原创查看详情>>>](https://github.com/beekeeper-studio/beekeeper-studio)

**Comment by buddy-red** [comment]
关闭此issue

**Comment by anicetrip** [comment]
所以需要在源代码层面替换掉源文件然后重新编译是吗？好的感谢。

**Comment by winter60** [comment]
请问windows下载哪个releases

**Comment by buddy-red** [comment]
> 请问windows下载哪个releases

没有生成，请自己构建。
